---
title: "NMF clustering"
author: "Dmitrii Belousov"
date: "2024-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      root.dir = "~/GVHD_project/notebooks/EDA/")
library(tidyverse)
library(ggplot2)
library(NMF)
library(Biobase)
library(pheatmap)
library(survival)
library(survminer)
```



```{r}
data <- read_csv("~/GVHD_project/data/data_wide_preproc.csv")
data <- data %>% 
  mutate(Event = ifelse(is.na(cGVHD_time), 0, 1),
         Time_CFS = ifelse(is.na(cGVHD_time), Time_OS, cGVHD_time))

row.names(data) <- data %>% 
  mutate(ID_new = paste0(round(runif(231, 0, 1000), 0), Collection_time, ID)) %>% 
  pull(ID_new)
```
```{r}
rownames(data)
```


```{r}
data %>% 
  filter(is.na(cGVHD_day) 
         & !is.na(Collection_time) 
         & Collection_Day %in% c("90") 
         & Collection_time != "Post") %>% 
  select(everything(), -c(ID, Time_OS, Time_CFS, cGVHD_time, cGVHD_day, 
                          Collection_Day, Source, cGVHD_time_discrete, 
                          Collection_time, Post_cGVHD_time)) %>% 
  mutate(across(-Event, log1p), 
         #across(-Event, scale), 
         Event = as.factor(Event)) -> data_filtered

event <- data_filtered %>% 
  pull(Event)

data_filtered <- data_filtered %>% 
  select(everything(), -Event) %>% 
  t() %>% 
  as.data.frame()

data_filtered_random <- randomize(data_filtered)
```

```{r}
estim.r.random <- nmf(data_filtered_random, 2:15, nrun=10, seed=42)
estim.r <- nmf(data_filtered, 2:15, nrun=10, seed=42)
```

```{r, fig.height=7, fig.width=12}
plot(estim.r, estim.r.random)
```
```{r fig.height=5, fig.width=8}
res <- nmf(data_filtered, 7, nrun=100, seed=42)

layout(cbind(1,2))
basismap(res, subsetRow=TRUE)
coefmap(res)
```
```{r}
summary(res)
```

```{r}
str(res)

```

```{r}
event <- as.data.frame(event)
rownames(event) <- paste0("V", rownames(event))

cc <- as.data.frame(predict(res))
colnames(cc) <- c("consensus")
```

```{r, fig.height=7, fig.width=10}
library(RColorBrewer)

event_colors <- setNames(brewer.pal(length(unique(event$event)), "Set2"), unique(event$event))
cc_colors <- setNames(brewer.pal(length(unique(cc$consensus)), "Pastel1"), unique(cc$consensus))

annotation_colors <- list(event = event_colors, consensus = cc_colors)

order <- cc %>% 
  arrange(consensus) %>% 
  rownames()

pheatmap::pheatmap(res@consensus[order, order], 
                     cellwidth = 6, cellheight = 6, 
                     cluster_rows = F, cluster_cols = F,
                     annotation_col = cbind(event, cc),
                     annotation_colors = annotation_colors,
                     border_color = NA)
```
```{r}
custom_colors <- colorRampPalette(c("#C9DAEE", "#68254C"))(50)
pheatmap::pheatmap(table(event$event, cc$consensus), 
                   cellwidth = 60, cellheight = 60, 
                   color = custom_colors, border_color = "black")
```

```{r}
column_proportions <- apply(table(event$event, cc$consensus) , 2, function(x) x / sum(x))
print(column_proportions)

custom_colors <- colorRampPalette(c("#C9DAEE", "#68254C"))(50)
pheatmap::pheatmap(column_proportions, 
                   cluster_rows = F, cluster_cols = F,
                   cellwidth = 60, cellheight = 60, 
                   color = custom_colors, border_color = "black")
```
```{r, fig.height=20, fig.width=5}
pheatmap::pheatmap(res@fit@W, 
                   cellwidth = 10, 
                   cellheight = 8, 
                   cluster_rows = T, 
                   cluster_cols = F,
                   border_color = NA, 
                   scale = "row")


```

```{r}
W <- res@fit@W
colnames(W) <- c(1:7)
top_features_all <- lapply(1:ncol(W), function(cluster) {
  sort(W[, cluster], decreasing = TRUE)[1:10]
})

names(top_features_all) <- paste0("Cluster_", 1:ncol(W))
print(top_features_all)

```

```{r, fig.height=6}
top_feature_names <- unique(unlist(lapply(top_features_all, names)))
W_top <- W[top_feature_names, ] 

pheatmap::pheatmap(t(W_top), 
                   cellwidth = 10, 
                   cellheight = 8, 
                   cluster_rows = F,
                   show_rownames = T,
                   cluster_cols = T, 
                   border_color = NA, 
                   scale = "row")
```

```{r}
data_filtered_t <- data_filtered %>% 
  t() %>% 
  as.data.frame()
```

```{r, fig.height=5}
ds_cfs <- data %>% 
  filter(is.na(cGVHD_day) 
         & !is.na(Collection_time) 
         & Collection_Day %in% c("90") 
         & Collection_time != "Post") %>% 
  select(c(ID, Time_CFS, Event)) %>% 
  as.data.frame()

rownames(ds_cfs) <- rownames(data_filtered_t)

ds_cfs_cc <- cbind(ds_cfs[rownames(cc),], cc) %>% filter(consensus != 7)

#ds_cfs_cc = ds_cfs_cc %>% filter(Event == 1) %>% filter(!(consensus %in% c(4, 6)))

surv_object <- Surv(time = as.numeric(ds_cfs_cc$Time_CFS), event = ds_cfs_cc$Event)

fit <- survfit(surv_object ~ consensus, data = ds_cfs_cc)

ggsurvplot(fit, 
           data = ds_cfs_cc,
           title = "Cluster survival curves",
           conf.int	= FALSE,        
           risk.table = TRUE,
           tables.height = 0.375,
           pval = TRUE,
           #xlim = c(0, 365),
           pval.coord = c(300, 0.99)) 
```

```{r}

```












